name: Swift

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build for macOS
        working-directory: BeFake Project
        run: swift build -v

  unit_test:
    name: Unit test
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
      UNIT_TEST_TARGET: "ActionsTests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Run macOS tests
        working-directory: BeFake Project/Tests
        run: swift test --enable-code-coverage
  Lint:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging
