name: Swift

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    container:
      image: swift:5.3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Lint code using SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  codecov:
    container:
      image: swift:5.3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --enable-code-coverage
    - uses: mattpolzin/swift-codecov-action@0.7.3
      with:
        MINIMUM_COVERAGE: 98
        INCLUDE_TESTS: 'true'