name: Swift

on:
  push:
    branches: [ $default-branch ]
    paths: '**.swift'
  pull_request:
    branches: [ $default-branch ]
    paths: '**.swift'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test